### ISSUE TITLE
Not entire AQL which is defined in Criteria will be executed by Retrieve Data

### ISSUE THREAD

**Issue by smnrdln** [NUM-Forschungsdatenplattform/num-portal-webapp#348]
Hi Guys,

we installed num-portal and num-portal-webapp at UKSH to experiment the features and getting connected to our current OpenEHR infrastructure.

Currently, we faced the following issue. After starting a project, by navigating to Data Retrieval and clicking on Retrieve Data, the filter which is defined at Criteria will not be applied correctly. 

for example, although the AQL in Criteria is defined like this:

```
SELECT
  e1/data[at0001]/items[at0002]/value/defining_code/code_string as code
FROM
  EHR e
  contains COMPOSITION c0[openEHR-EHR-COMPOSITION.report.v1]
  contains EVALUATION e1[openEHR-EHR-EVALUATION.problem_diagnosis.v1]
WHERE
  (c0/archetype_details/template_id/value = 'KDS_Diagnose'
  AND e1/data[at0001]/items[at0002]/value/defining_code/code_string LIKE 'I50*')
```

the UI will send this AQL to num-portal:

```
SELECT
  c0 as KDS_Diagnose
FROM
  EHR e
  contains COMPOSITION c0[openEHR-EHR-COMPOSITION.report.v1]
WHERE
  c0/archetype_details/template_id/value = 'KDS_Diagnose'
```

which doesn't contain  " code_string LIKE 'I50*' " part and all data will be shown which is not desired. For this example we defined a Criteria, and it will be used for defining a project. But after staring the project, all the data which contains a specific "template_id" (here KDS_Diagnose) will be returned and the other filters will be ignored.

Could you please let us know if this is the way it supposed to behave or where could be the problem.

Thanks!

**Comment by ppazos** [comment]
I have checked, just in case, that the AQL was parsed correctly by the grammar.

```
java -jar antlr-4.10.1-complete.jar Aql.g4 -visitor
javac -classpath antlr-4.10.1-complete.jar [Aql*.java](http://Aql*.java)
java -classpath .:antlr-4.10.1-complete.jar org.antlr.v4.gui.TestRig Aql query -gui test.aql
```

The grammar is here https://github.com/ehrbase/ehrbase/blob/develop/service/src/main/antlr4/org/ehrbase/aql/parser/Aql.g4

`test.aql` is your original query

Output:

![antlr4_parse_tree](https://user-images.githubusercontent.com/1278556/179652096-d58e0464-b3b9-49d7-850a-3383004b281c.png)

**Comment by smnrdln** [comment]
num-portal uses openEHR_SDK [v1.5.0](https://github.com/ehrbase/openEHR_SDK) but the lastest version is [v1.19.0](https://github.com/ehrbase/openEHR_SDK/releases/tag/v1.19.0). Might an upgrade help to solve the problem?

**Comment by ppazos** [comment]
The only change between those versions in the method that seems to generate the issue is the error handler, I don't think that will solve this but you can try updating the dependency.

https://github.com/ehrbase/openEHR_SDK/blame/v1.19.0/aql/src/main/java/org/ehrbase/aql/parser/AqlToDtoParser.java

**Comment by smnrdln** [comment]
Yes, it seems the update doesn't change anything in this regard. I did that and there were some inconsistencies at different parts of the code. I just somehow managed to get it running again, but it didn't change anything regarding this issue. Should an issue be created in openEHR_SDK? This seems to be a high-priority bug if AQL Queries don't work appropriately.
